workflows:
  version: 2
  build:
    jobs:
      - lint
      - test-mattermost-esr:
          requires:
            - lint
      - test-mattermost-latest:
          requires:
            - lint
      - test-mattermost-previous:
          requires:
            - lint
      - test-mattermost-previous2:
          requires:
            - lint
      - sonarqube:
          requires:
            - lint
            - test-mattermost-esr
            - test-mattermost-latest
 
version: 2
jobs:
  lint:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8u212-jdk-stretch
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn verify -DskipTests=true --show-version
  test-mattermost-base: &test-mattermost-base
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8u212-jdk-stretch
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: mostest
          MYSQL_USER: mmuser
          MYSQL_PASSWORD: mostest
          MYSQL_DATABASE: mattermost_test
      - image: jhillyerd/inbucket:release-2.0.0
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - run:
          name: setup-mattermost-server
          command: |
              mkdir ~/work
              wget https://releases.mattermost.com/${MATTERMOST_VERSION}/mattermost-team-${MATTERMOST_VERSION}-linux-amd64.tar.gz -O ~/work/mattermost.tar.gz
              tar -C ~ -xvf ~/work/mattermost.tar.gz
              [ -e ~/mattermost/config/default.json ] && cp ~/mattermost/config/default.json ~/mattermost/config/config.json
              sed -e 's/dockerhost/localhost/' -e 's/\("EnableUploads": \)false/\1true/' -i ~/mattermost/config/config.json
      - run: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: mattermost
          command: cd ~/mattermost && ~/mattermost/bin/platform
          background: true
      - checkout
      - run: for i in 1 2 3 4 5 6 7 8 9 10; do curl -I "${MATTERMOST_URL:-http://localhost:8065}" || sleep 10 && continue; break; done
      - run: mvn verify --show-version
      - run:
          name: Prepare test results
          command: |
              mkdir -p ~/test-results/
              find . -type f -regex ".*/target/failsafe-reports/.*xml" -o -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/ \;
          when: always
      - store_test_results:
          path: ~/test-results

  test-mattermost-esr:
    <<: *test-mattermost-base
    environment:
      MATTERMOST_VERSION: 5.9.3
  test-mattermost-latest:
    <<: *test-mattermost-base
    environment:
      MATTERMOST_VERSION: 5.14.0
  test-mattermost-previous:
    <<: *test-mattermost-base
    environment:
      MATTERMOST_VERSION: 5.13.2
  test-mattermost-previous2:
    <<: *test-mattermost-base
    environment:
      MATTERMOST_VERSION: 5.12.5
  sonarqube: 
    <<: *test-mattermost-base
    environment:
      MATTERMOST_VERSION: 5.14.0
    steps:
      - run:
          name: setup-mattermost-server
          command: |
              mkdir ~/work
              wget https://releases.mattermost.com/${MATTERMOST_VERSION}/mattermost-team-${MATTERMOST_VERSION}-linux-amd64.tar.gz -O ~/work/mattermost.tar.gz
              tar -C ~ -xvf ~/work/mattermost.tar.gz
              [ -e ~/mattermost/config/default.json ] && cp ~/mattermost/config/default.json ~/mattermost/config/config.json
              sed -e 's/dockerhost/localhost/' -e 's/\("EnableUploads": \)false/\1true/' -i ~/mattermost/config/config.json
      - run: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: mattermost
          command: cd ~/mattermost && ~/mattermost/bin/platform
          background: true
      - checkout
      - run: dockerize -wait tcp://127.0.0.1:8065 -timeout 120s
      - run: mvn clean verify sonar:sonar --show-version -s .circleci/settings-sonar.xml
      - run:
          name: Prepare test results
          command: |
              mkdir -p ~/test-results/
              find . -type f -regex ".*/target/failsafe-reports/.*xml" -o -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/ \;
          when: always
      - store_test_results:
          path: ~/test-results

